import Head from "next/head";
import Hero from "../components/Hero";
import ProjectList from "~/components/ProjectList";
import Contact from "~/components/Contact";
import ResponsiveNavbar from "~/components/ResponsiveNavbar";
import { useRef } from "react";

export default function Home() {
  const homeRef = useRef<null | HTMLDivElement>(null);
  const aboutRef = useRef<null | HTMLDivElement>(null);
  const projectRef = useRef<null | HTMLDivElement>(null);
  const contactRef = useRef<null | HTMLDivElement>(null);

  const homeClick = () => {
    homeRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const aboutClick = () => {
    aboutRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const projectClick = () => {
    projectRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const contactClick = () => {
    contactRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  const header = {
    title: "Welcome to my portfolio",
    description:
      "A full stack developer looking for opportunities from freelance to full-time. My favorite technologies are ReactJS based. Check out my portfolio.",
  };

  const about = {
    title: "About me",
    description:
      "Coding is my passion, especially in the ReactJS ecosystem. What I enjoy the most is rethinking how I code my projects. I think that coding is a world full of possibilities. Why do things one way when there are tons of possibilities for innovation? I'm open to ideas and would like to collaborate on some new projects and ideas. Let's connect!",
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResponsiveNavbar
        handleHomeClick={homeClick}
        handleAboutClick={aboutClick}
        handleProjectClick={projectClick}
        handleContactClick={contactClick}
      />
      <main className="flex min-h-screen flex-col items-center ">
        <div ref={homeRef}>
          <Hero title={header.title} description={header.description} />
        </div>
        <div ref={aboutRef} className="w-[100%] bg-black text-white">
          <Hero title={about.title} description={about.description} />
        </div>
        <div ref={projectRef} className="pt-32">
          <ProjectList />
        </div>
        <div ref={contactRef}>
          <Contact />
        </div>
      </main>
    </>
  );
}
