import Head from "next/head";
import Hero from "../components/Hero";
import ProjectList from "~/components/ProjectList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center ">
        <Hero />
        <ProjectList />
      </main>
    </>
  );
}
